#!/bin/zsh
#
# Manjaro Image *.sig file Check

function manjaro_sig_check() {
  #[[ ! -e $HOME/.gnupg/manjaro.gpg ]]


  echo "";echo "Downloading Keys......";echo "";
  wget -q https://github.com/manjaro/packages-core/raw/master/manjaro-keyring/manjaro.gpg;
  echo ""; # newline
  gpg --import manjaro.gpg;
  echo ""; # newline
  echo "PAY ATTENTION NOW!!!!!";
  gpg --verify $@;
  rm -f manjaro.gpg (m0);
}
